### ISSUE TITLE
Frontend seems corrupt

### ISSUE THREAD

**Issue by JanCizmar** [sebischair/sebamaster-movie-frontend#1]
Hello,

1. I think the html in the index.html is corrupt, i changed it to this and now it works:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Movie app</title>
</head>

<body>

<div id="app"></div>

</body>
</html>
```

2. It throws an error about not defined style of Card element/component in MovieDetail.js, so i deleted the style attribute and now it works.

Your Team 43.

**Comment by GlaserIngo** [comment]
Hi,

thanks for the information. 

Concerning 1:
The HTML itself was just "corrupt" on the master branch, while serverless was already fine. However, this did not cause any problems either way.

Regarding 2:
We forgot to remove the style attribute in the serverless branch, while it was already removed in the master branch.

The repository should be in a good shape now.

Best,
Ingo
